src/objects/Client_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NB: TO ADD NEW STATUS FIRST OPEN REFERRAL **</relationshipLabel>
        <relationshipName>Client_Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Date__c</fullName>
        <label>Outcome Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <label>Referral</label>
        <referenceTo>Client_Referral__c</referenceTo>
        <relationshipLabel>Client Status &amp; Outcomes</relationshipLabel>
        <relationshipName>Client_Placements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Client Status &amp; Outcomes</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Status &amp; Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Client_Referral__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Referrals</relationshipLabel>
        <relationshipName>Client_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referred_By__c</fullName>
        <label>Referred By</label>
        <picklist>
            <picklistValues>
                <fullName>Addiction Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ademilola adesida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agnes M. Scully</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aidan P. Trant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aideen M. McDonnell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aine E. Connolly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aine E. Morris</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aine M. Murray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aishling C. Bolger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alan I. Doyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alan M. Hughes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alice Garvin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma M. Gavin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amanda Egan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambrose O&apos;Byrne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andrea D. Devine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andrea M. Bourke</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andrew J. Murphy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andy Crow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anita I. Charles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ann A. OFarrell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna M. AlgostssonGallagher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna M. BradyWilliams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna M.Connolly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna M. Corcoran</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna Stoller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna T. Rynn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ann B. Ryan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Conway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne J. Ansbro</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client Referral</label>
    <nameField>
        <displayFormat>CF-{00000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Referrals</pluralLabel>
    <recordTypes>
        <fullName>Linkage</fullName>
        <active>true</active>
        <label>Linkage</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Web_HR_Absence__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_No__c</fullName>
        <label>Employee No.</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>No_of_Days__c</fullName>
        <label>No. of Days</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Return_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Study Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uncertified Sick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified Sick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maternity Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Unpaid Maternity Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Force Majeure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paternity Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compassionate Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funeral Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bereavement Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Statutory Maternity Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carers Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exam Leave</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Your_Name__c</fullName>
        <label>Your Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Web HR-Absence</label>
    <nameField>
        <displayFormat>WHR-{00000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Web HR-Absences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestClasses.cls
@isTest
public class TestClasses 
{
 	public static testMethod void testSearch ()
    {
//    	createContacts (10);
 
        
     	FindClientController tc = new FindClientController();
    	tc.searchLastNameString = 'Smith';
    	
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    	tc.Search();
		
		PageReference pageRef = Page.FindClientPage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('lastname', 'Smith');
        tc.performSearch();
    }

 	public static testMethod void testSecureDataArea ()
    {
     	List <Contact> contacts = createContacts (10);

 		ApexPages.StandardController contactPage = new ApexPages.StandardController(contacts[0]);
 
      	SecureDataController tc = new SecureDataController(contactPage);
      	tc.clearFields();
    	tc.loadSensitiveData();
    	tc.saveSensitiveData();
    }
    
	@isTest(SeeAllData=true)
 	public static void testSecureDataAreaWithMockResponse ()
    {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

		Contact testContact = [select ID from Contact limit 1];
 		ApexPages.StandardController contactPage = new ApexPages.StandardController(testContact);
 
      	SecureDataController tc = new SecureDataController(contactPage);
    	tc.loadSensitiveData();
    	tc.saveSensitiveData();
    }
    
    public static List<Contact>  createContacts (Integer nContacts)
    {
    	List<Contact> newContacts = new List<Contact>();
    	ID clientType = [select ID from RecordType where Name = 'Client' limit 1].id;
    	for (Integer i=1; i<=nContacts; i++)
    	{
    		Contact c = new Contact (LastName='Client' + i, RecordTypeID = clientType);
    		newContacts.add (c);
    	}	
    	insert newContacts;
    	
    	createIdentifiableClients ();
    	
    	return newContacts;
    }
    
    public static Map<String, IdentifiableClient> createIdentifiableClients ()
    {
     	ID clientType = [select ID from RecordType where Name = 'Client' limit 1].id;
    	Map<String, IdentifiableClient> ics = new Map <String, IdentifiableClient> ();
    	List<Contact> contacts = [select ID, LastName from Contact where RecordTypeID = :clientType];
    	for (Contact oneC: contacts)
    	{
    		IdentifiableClient ic = new IdentifiableClient ();
    		ic.Ref = oneC.LastName;
    		ic.details=oneC;
    		ics.put (ic.Ref, ic);
    	}
    	return ics;
    }
    
    public static List<Client_Referral__c> createReferrals (List<Contact> contacts, Integer nCount)
    {
     	Date lastMonth = system.today() - 28;
    	List <Client_Referral__c> refs = new List<Client_Referral__c>();
    	
     	ID referralType = [select ID from RecordType where Name = 'Linkage' and sObjectType = 'Client_Referral__c' limit 1].id;
    	for (Contact oneContact: contacts)
    	{
	    	for (Integer i=1; i<nCount; i++)
    		{
    			Client_Referral__c cr = new Client_Referral__c (Client__c = oneContact.id, Referred_By__c = 'Fred', RecordTypeID=referralType);
    			refs.add (cr);
    		}
    	}
    	insert refs;
    	return refs;
    }
    
    public static List<Client_Outcome__c> createOutcomes (List<Client_Referral__c> referrals, Integer nCount)
    {
    	Date lastMonth = system.today() - 28;
    	List <Client_Outcome__c> outcomes = new List<Client_Outcome__c>();
    	
    	for (Client_Referral__c oneRef: referrals)
    	{
	    	for (Integer i=1; i<nCount; i++)
    		{
    			Client_Outcome__c oc = new Client_Outcome__c (Placement_Date__c = lastMonth + i, Referral__c = oneRef.id);
    			outcomes.add (oc);
    		}
    	}
    	insert outcomes;
    	return outcomes;
    }
    
    public static testMethod void testMonthlyReport ()
    {
     	List<Contact> nc = createContacts (10);
     	List<Client_Referral__c> cr = createReferrals (nc, 10);
     	List<Client_Outcome__c> oc = createOutcomes (cr, 10);
     	ReportParametersClass params = new ReportParametersClass();
     	params.save();
    	//MonthlyReferralsController mc = new MonthlyReferralsController ();
    }

	@isTest(SeeAllData=true)
    public static void testMonthlyReportWithMockResponse ()
    {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
     	ReportParametersClass params = new ReportParametersClass();
     	params.save();
    	MonthlyReferralsController mc = new MonthlyReferralsController ();
    }
    
    public static testMethod void testHRWebAbsence ()
    {
    	Contact c = new Contact (LastName='Fred', Employee_ID__c = '1');
    	insert c;
		Web_HR_Absence__c whra= new Web_HR_Absence__c (Employee_No__c='1', Your_Name__c = 'Fred', Email_Address__c='test@test.com', Start_Date__c=system.today(),No_of_Days__c=2,Return_Date__c=system.today()+1,Type__c='Certified Sick',Comments__c='Cold');
		insert whra;
    }
}