src/objects/Client_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NB: TO ADD NEW STATUS FIRST OPEN REFERRAL **</relationshipLabel>
        <relationshipName>Client_Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outcome_Types__c</fullName>
        <label>Final Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Addiction Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apprenticeship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE Scheme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Service Placement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR Resettlement Support Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged But Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full-time Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full-time Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full-time Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guidance Only Complete (HRO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IASIO group work programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jobs Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Literacy Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PACE on TR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part-time Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part-time Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part-time Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATHWAYS on TR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Protocol referral to Intreo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resettlement Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supported access to essential services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supported stability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Workshop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Placement_Date__c</fullName>
        <label>Outcome Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Programme__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <label>Referral</label>
        <referenceTo>Client_Referral__c</referenceTo>
        <relationshipLabel>Client Status &amp; Outcomes</relationshipLabel>
        <relationshipName>Client_Placements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brief Intervention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE Scheme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged but Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Time Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Time Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inappropriate Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intra-programme transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Met To Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Progression Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Time Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Time Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resettled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resettlement Plan Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supported Referral to Another Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer to another TEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unexpected Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Start Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred to Guidance and Placement Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRRS Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guidance Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client Status &amp; Outcomes</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Status &amp; Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Client_Referral__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Referrals</relationshipLabel>
        <relationshipName>Client_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Status_Outcome_Date__c</fullName>
        <label>First Status/Outcome Date</label>
        <summarizedField>Client_Outcome__c.Placement_Date__c</summarizedField>
        <summaryForeignKey>Client_Outcome__c.Referral__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Programme__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referral_ID__c</fullName>
        <label>Referral ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referral_Type__c</fullName>
        <label>Referred For</label>
        <picklist>
            <picklistValues>
                <fullName>Community Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guidance &amp; Placement Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guidance Only (HRSO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resettlement Support (CRRS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YPP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referred_By__c</fullName>
        <label>Referred By</label>
        <picklist>
            <picklistValues>
                <fullName>Addiction Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ademilola adesida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agnes M. Scully</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aidan P. Trant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aideen M. McDonnell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aine E. Connolly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aine E. Morris</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aine M. Murray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aishling C. Bolger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alan I. Doyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alan M. Hughes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alice Garvin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma M. Gavin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amanda Egan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambrose O&apos;Byrne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andrea D. Devine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andrea M. Bourke</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andrew J. Murphy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andy Crow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anita I. Charles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ann A. OFarrell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna M. AlgostssonGallagher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna M. BradyWilliams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna M.Connolly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna M. Corcoran</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna Stoller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anna T. Rynn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ann B. Ryan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Conway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne J. Ansbro</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referred_From__c</fullName>
        <label>Referred From</label>
        <picklist>
            <picklistValues>
                <fullName>Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred From blank</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client Referral</label>
    <nameField>
        <displayFormat>CF-{00000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Referrals</pluralLabel>
    <recordTypes>
        <fullName>Linkage</fullName>
        <active>true</active>
        <label>Linkage</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MonthlyReferralsController.cls
public with sharing class MonthlyReferralsController 
{
	private secure_settings__c settings;
	public List<IdentifiableClient> clients {get;set;}
	private List<IdentifiableClient> allClients;
	
	public Date startDate {get;set;}
	public Date endDate {get;set;}
	
	public MonthlyReferralsController ()
	{
    	settings = secure_settings__c.getOrgDefaults();
		Initialise ();
	}

	private void Initialise ()
	{
		calculateReportDate ();
		
		Map<ID,Client_Outcome__c> outcomes = new Map<ID,Client_Outcome__c>([select ID, Placement_Date__c, Referral__c from Client_Outcome__c where Placement_Date__c >= :startDate and Placement_Date__c < :endDate and Referral__r.Programme__c LIKE 'Linkage%']);
		Set <ID> referralSet = new Set<ID>();
		for (Client_Outcome__c oneOutcome: outcomes.Values())
			referralSet.add (oneOutcome.Referral__c);
		
		
		Map<ID, Client_Referral__c> referrals = new Map<ID, Client_Referral__c>([select ID, Name, Client__c, Referral_ID__c, Referral_Type__c, Referred_From__c, First_Status_Outcome_Date__c, Referred_By__c, OwnerID, (select ID, Placement_Date__c, Status__c, Outcome_Types__c, Reason_for_Discontinued__c  from Client_Placements__r order by Placement_Date__c DESC) from Client_Referral__c where ID in :referralSet]);
		Set <ID> clientSet = new Set<ID>();
		Set <ID> referralOwnersSet = new Set<ID>();
		for (Client_Referral__c oneReferral: referrals.Values())
		{
			clientSet.add (oneReferral.Client__c);
			referralOwnersSet.add (oneReferral.OwnerId);
		}
			
		Map<ID,User> referralOwners = new Map<ID,User>([select ID, Name from User where ID in :referralOwnersSet]); 
		List<Contact> clientContacts = [select ID, LastName, Client_Ref__c, Birthdate, Gender__c, Client_Nationality__c, (select ID, First_Status_Outcome_Date__c , ReferralDate__c from Client_Referrals__r order by ReferralDate__c ASC) from Contact where ID in :clientSet];
		
		clients = getClients (clientContacts);
		
		// now we have the clients, fill in the details needed for the report
		for (IdentifiableClient oneClient: clients)
		{
			oneClient.FirstReferralDate = null; 
			for (Client_Referral__c oneReferral: oneClient.details.Client_Referrals__r)
			{
				if (referralSet.contains (oneReferral.id)) // is this a referral I am interested in
				{
					if (oneClient.FirstReferralDate == null) 
					{
						oneClient.FirstReferralDate = oneReferral.ReferralDate__c; // this is the first referral date on the client during the time period of the report (date of referral in the report)
						oneClient.StartDateFirstMeeting = oneReferral.First_Status_Outcome_Date__c; // this is the oldest status and outcome date linked to the first referral
					}
					Client_Referral__c thisClientsReferral = referrals.get (oneReferral.Id);
					oneClient.ProbationOfficer = thisClientsReferral.Referred_By__c;
					oneClient.Owner = referralOwners.get(thisClientsReferral.OwnerId).Name;
					oneClient.referralID = thisClientsReferral.Name; // Adele asked for the Name of the referral rather than the referral ID EK 29/4/2014
					oneClient.referredFrom = thisClientsReferral.Referred_From__c;
					oneClient.referredFor = thisClientsReferral.Referral_Type__c;
					if (thisClientsReferral != null && thisClientsReferral.Client_Placements__r != null && thisClientsReferral.Client_Placements__r.size() > 0)
					{
						for (Client_Outcome__c oneOutcome: thisClientsReferral.Client_Placements__r)
						{
							if (outcomes.keySet().contains (oneOutcome.id))
							{
								oneClient.OutcomeDate = oneOutcome.Placement_Date__c;
								oneClient.OutcomeStatus = oneOutcome.Outcome_Types__c;
								oneClient.Status = oneOutcome.Status__c;
								if (oneClient.Status == 'Engaged but Discontinued') oneClient.DateDiscontinued = oneClient.OutcomeDate;
								if (oneClient.Status == 'Placed') oneClient.DateCompleted = oneClient.OutcomeDate;
								oneClient.ReasonDiscontinued = oneOutcome.Reason_for_Discontinued__c;
								
								oneClient.lineYear = oneOutcome.Placement_Date__c.year();
								DateTime d = date.newInstance(oneClient.lineYear, oneOutcome.Placement_Date__c.month(), 1);
								oneClient.lineMonth = d.format('MMMMM');
								break; // out of the for loop as only one outcome is counted
							}
						}
					}
					break; // out of the for loop
				}
			}
			
		}
	}	
	
	private void calculateReportDate ()
	{
		if (!test.isRunningTest())
		{
			startDate = Date.parse(ApexPages.currentPage().getParameters().get('start'));
			endDate = Date.parse(ApexPages.currentPage().getParameters().get('end')).addDays (1);
		}
		else 
		{
			startDate = date.newInstance(system.today().year(), system.today().month() - 1, 1);
			endDate = date.newInstance(system.today().year(), system.today().month() + 1, 1) - 1;
		}
	}
	
	// run the search and match against the contacts.
  	public List<IdentifiableClient> getClients(List<Contact> reportContacts) 
  	{
  		List<IdentifiableClient> searchResults = new List<IdentifiableClient>();
  		
  		String clientIDs = '';
  		for (Contact oneClient: reportContacts)
  			clientIDs += oneClient.lastName + ',';
  		clientIDs = clientIDs.removeEnd (',');
  			
        String url = settings.baseURL__c + 'clientsList/' + clientIDs + '/' + settings.Username__c + '/' + settings.Key__c + '/' + settings.Secret__c + '/';
        system.debug ('In getClients url: ' + url);
 		Map<String, IdentifiableClient> clientMap = new Map<String, IdentifiableClient>();
		try
		{
//			Map<String, Object> m= (Map<String, Object>)JSON.deserializeUntyped(RestHelpers.getContent (url));
//			for (Object oneClient: (List<Object>)m.get('objects'))
			for (Object oneClient: (List<Object>)JSON.deserializeUntyped(RestHelpers.getContent (url)))
			{
				Map<String, Object> workingClient = (Map<String, Object>)oneClient;
				system.debug ('Client: ' + (String)workingClient.get('ID'));
				IdentifiableClient newClient = new IdentifiableClient ();
				newClient.FirstName = (String)workingClient.get('firstName');
				newClient.LastName = (String)workingClient.get('lastName');
				newClient.Ref = (String)workingClient.get('ID');
				clientMap.put (newClient.Ref, newClient);
			}
		}
		catch (Exception e)
		{
			system.debug (e.getMessage());
		}

		for (Contact oneContact: reportContacts)
		{
			IdentifiableClient oneClient = clientMap.get (oneContact.LastName);
			if (oneClient != null) 
			{
				oneClient.details = oneContact;
				searchResults.add (oneClient);
			}
		}
		
		system.debug ('In getClients, found: ' + searchResults.size() + ' clients');
  		return searchResults;
 	}
}