src/objects/Report_Parameters__c.object
<CustomObject>
    <description>Parameters for the referral report - INTERNAL USE ONLY</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>DATE(2013,9,30)</defaultValue>
        <inlineHelpText>Dates are inclusive</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Dates are inclusive</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Report Parameters</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Report Parameters Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReportParametersClass.cls
public with sharing class ReportParametersClass 
{
	public Report_Parameters__c params {get;set;}
	
	public ReportParametersClass ()
	{
		params = new Report_Parameters__c ();
		calculateDefaultDates ();
	}
	
	public PageReference Save()
	{
		PageReference reportPage = new PageReference ('/apex/MonthlyReferralsPage?start=' + params.Start_Date__c.format() + '&end=' + params.End_Date__c.format());
		return reportPage;
	}
	
	private void calculateDefaultDates ()
	{
		Integer reportMonth = system.today().month() - 1;
		Integer reportYear = system.today().year();
		if (reportMonth == 0)
		{
			reportMonth = 12;
			reportYear--;
		}
		params.Start_date__c = Date.newInstance (reportYear, reportMonth, 1);
		params.End_date__c = Date.newInstance (reportYear, reportMonth+1, 1) - 1;
	}
	
}